apiVersion: apps/v1
kind: Deployment
metadata:
  name: garbage-load-balancer
  labels:
    app: garbage-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garbage-load-balancer
  template:
    metadata:
      labels:
        app: garbage-load-balancer
    spec:
      nodeSelector:
        nodeType: "228"
      containers:
      - name: garbage-load-balancer
        image: localhost:5000/k_ogawa/garbage-load-balancer:v1
        command: ["/bin/bash"]
        args: ["/app/run.sh", "4"]


