apiVersion: apps/v1
kind: Deployment
metadata:
  name: garbage-detect-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garbage-detect-listener
      tier: backend
  template:
    metadata:
      labels:
        app: garbage-detect-listener
        tier: backend
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        nodeType: "228"
      containers:
      - name: garbage-detect-listener
        image: localhost:5000/k_ogawa/garbage-detect-listener:v1
        #command: ["/bin/sleep"]
        #args: ["20000"]
        command: ["/bin/bash"]
        args: ["/app/run.sh", "2"]
        ports:
        - containerPort: 8194
        #resources:
        #  limits:
        #    cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: garbage-detect-listener
spec:
  type: LoadBalancer
  selector:
    app: garbage-detect-listener
  ports:
  - protocol: TCP
    port: 8194
    targetPort: 8194
