apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-load-balancer
  labels:
    app: road-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: road-load-balancer
  template:
    metadata:
      labels:
        app: road-load-balancer
    spec:
      nodeSelector:
        nodeType: "228"
      containers:
      - name: road-load-balancer
        image: localhost:5000/k_ogawa/road-load-balancer:v1
        command: ["/bin/bash"]
        args: ["/app/run.sh", "8"]


