apiVersion: apps/v1
kind: Deployment
metadata:
  name: road-damage-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: road-damage-listener
      tier: backend
  template:
    metadata:
      labels:
        app: road-damage-listener
        tier: backend
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        nodeType: "228"
      containers:
      - name: road-damage-listener
        image: localhost:5000/k_ogawa/road-damage-listener:v1
        command: ["/bin/bash"]
        args: ["/app/run.sh", "8"]
        #command: ["/bin/sleep"]
        #args: ["20000"]
        ports:
        - containerPort: 8199
        #resources:
        #  limits:
        #    cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: road-damage-listener
spec:
  type: LoadBalancer
  selector:
    app: road-damage-listener
  ports:
  - protocol: TCP
    port: 8199
    targetPort: 8199
