apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-load-balancer
  labels:
    app: yolo-load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-load-balancer
  template:
    metadata:
      labels:
        app: yolo-load-balancer
    spec:
      nodeSelector:
        nodeType: "228"
      containers:
      - name: yolo-load-balancer
        image: localhost:5000/k_ogawa/yolo_load_balancer:v1
        command: ["/bin/bash"]
        args: ["/app/run.sh", "8"]

